version: 2

seeds:
    - name: employees
      description: a manually loaded employees data file.
      columns:
        - name: employee_id
          tests:
            - unique
            - not null
