version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        tests:
            - unique
            - not_null
      - name: first_order_date
        description: NULL when customer didnt place any order.

  - name: stg_customer
    description: This model cleans up the customer data.
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      
  - name: stg_order
    description: This model cleans up the orders data.
    columns:
      - name: order_id
        tests:
            - unique
            - not_null

      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
            
      - name: customer_id
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')
              
            